//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Microsoft.Samples.UserName
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.Samples.UserName", ConfigurationName="Microsoft.Samples.UserName.ICalculator")]
    public interface ICalculator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/GetCallerIdentity", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/GetCallerIdentityResponse")]
        string GetCallerIdentity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/GetCallerIdentity", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/GetCallerIdentityResponse")]
        System.Threading.Tasks.Task<string> GetCallerIdentityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Add", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/AddResponse")]
        double Add(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Add", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Subtract", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/SubtractResponse")]
        double Subtract(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Subtract", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/SubtractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Multiply", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/MultiplyResponse")]
        double Multiply(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Multiply", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Divide", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/DivideResponse")]
        double Divide(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Divide", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Upload", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/UploadResponse")]
        int Upload(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.UserName/ICalculator/Upload", ReplyAction="http://Microsoft.Samples.UserName/ICalculator/UploadResponse")]
        System.Threading.Tasks.Task<int> UploadAsync(System.IO.Stream data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : Microsoft.Samples.UserName.ICalculator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<Microsoft.Samples.UserName.ICalculator>, Microsoft.Samples.UserName.ICalculator
    {
        
        public CalculatorClient()
        {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetCallerIdentity()
        {
            return base.Channel.GetCallerIdentity();
        }
        
        public System.Threading.Tasks.Task<string> GetCallerIdentityAsync()
        {
            return base.Channel.GetCallerIdentityAsync();
        }
        
        public double Add(double n1, double n2)
        {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double n1, double n2)
        {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public double Subtract(double n1, double n2)
        {
            return base.Channel.Subtract(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double n1, double n2)
        {
            return base.Channel.SubtractAsync(n1, n2);
        }
        
        public double Multiply(double n1, double n2)
        {
            return base.Channel.Multiply(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2)
        {
            return base.Channel.MultiplyAsync(n1, n2);
        }
        
        public double Divide(double n1, double n2)
        {
            return base.Channel.Divide(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double n1, double n2)
        {
            return base.Channel.DivideAsync(n1, n2);
        }
        
        public int Upload(System.IO.Stream data)
        {
            return base.Channel.Upload(data);
        }
        
        public System.Threading.Tasks.Task<int> UploadAsync(System.IO.Stream data)
        {
            return base.Channel.UploadAsync(data);
        }
    }
}
