//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STS.RelyingPartyApp.SampleServiceOne {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleServiceOne.ISampleServiceOne")]
    public interface ISampleServiceOne {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceOne/ComputeResponse", ReplyAction="http://tempuri.org/ISampleServiceOne/ComputeResponseResponse")]
        string ComputeResponse(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceOne/ComputeResponse", ReplyAction="http://tempuri.org/ISampleServiceOne/ComputeResponseResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceOne/ComputeResponseAdmin", ReplyAction="http://tempuri.org/ISampleServiceOne/ComputeResponseAdminResponse")]
        string ComputeResponseAdmin(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceOne/ComputeResponseAdmin", ReplyAction="http://tempuri.org/ISampleServiceOne/ComputeResponseAdminResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseAdminAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceOne/ComputeResponseSuperAdmin", ReplyAction="http://tempuri.org/ISampleServiceOne/ComputeResponseSuperAdminResponse")]
        string ComputeResponseSuperAdmin(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceOne/ComputeResponseSuperAdmin", ReplyAction="http://tempuri.org/ISampleServiceOne/ComputeResponseSuperAdminResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseSuperAdminAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleServiceOneChannel : STS.RelyingPartyApp.SampleServiceOne.ISampleServiceOne, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceOneClient : System.ServiceModel.ClientBase<STS.RelyingPartyApp.SampleServiceOne.ISampleServiceOne>, STS.RelyingPartyApp.SampleServiceOne.ISampleServiceOne {
        
        public SampleServiceOneClient() {
        }
        
        public SampleServiceOneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceOneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceOneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceOneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ComputeResponse(string input) {
            return base.Channel.ComputeResponse(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseAsync(string input) {
            return base.Channel.ComputeResponseAsync(input);
        }
        
        public string ComputeResponseAdmin(string input) {
            return base.Channel.ComputeResponseAdmin(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseAdminAsync(string input) {
            return base.Channel.ComputeResponseAdminAsync(input);
        }
        
        public string ComputeResponseSuperAdmin(string input) {
            return base.Channel.ComputeResponseSuperAdmin(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseSuperAdminAsync(string input) {
            return base.Channel.ComputeResponseSuperAdminAsync(input);
        }
    }
}
