//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STS.RelyingPartyApp.SampleServiceTwo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleServiceTwo.ISampleServiceTwo")]
    public interface ISampleServiceTwo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceTwo/ComputeResponse", ReplyAction="http://tempuri.org/ISampleServiceTwo/ComputeResponseResponse")]
        string ComputeResponse(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceTwo/ComputeResponse", ReplyAction="http://tempuri.org/ISampleServiceTwo/ComputeResponseResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceTwo/ComputeResponseAdmin", ReplyAction="http://tempuri.org/ISampleServiceTwo/ComputeResponseAdminResponse")]
        string ComputeResponseAdmin(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceTwo/ComputeResponseAdmin", ReplyAction="http://tempuri.org/ISampleServiceTwo/ComputeResponseAdminResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseAdminAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceTwo/ComputeResponseSuperAdmin", ReplyAction="http://tempuri.org/ISampleServiceTwo/ComputeResponseSuperAdminResponse")]
        string ComputeResponseSuperAdmin(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleServiceTwo/ComputeResponseSuperAdmin", ReplyAction="http://tempuri.org/ISampleServiceTwo/ComputeResponseSuperAdminResponse")]
        System.Threading.Tasks.Task<string> ComputeResponseSuperAdminAsync(string input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleServiceTwoChannel : STS.RelyingPartyApp.SampleServiceTwo.ISampleServiceTwo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceTwoClient : System.ServiceModel.ClientBase<STS.RelyingPartyApp.SampleServiceTwo.ISampleServiceTwo>, STS.RelyingPartyApp.SampleServiceTwo.ISampleServiceTwo {
        
        public SampleServiceTwoClient() {
        }
        
        public SampleServiceTwoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceTwoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceTwoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceTwoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ComputeResponse(string input) {
            return base.Channel.ComputeResponse(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseAsync(string input) {
            return base.Channel.ComputeResponseAsync(input);
        }
        
        public string ComputeResponseAdmin(string input) {
            return base.Channel.ComputeResponseAdmin(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseAdminAsync(string input) {
            return base.Channel.ComputeResponseAdminAsync(input);
        }
        
        public string ComputeResponseSuperAdmin(string input) {
            return base.Channel.ComputeResponseSuperAdmin(input);
        }
        
        public System.Threading.Tasks.Task<string> ComputeResponseSuperAdminAsync(string input) {
            return base.Channel.ComputeResponseSuperAdminAsync(input);
        }
    }
}
